image:
  file: .gitpod.Dockerfile
ports:
- port: 3306
  onOpen: ignore
- port: 8080
  onOpen: open-preview
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'